#source:      _posts
destination: _site
layouts:     _layouts
permalink: /:title

markdown: redcarpet 
redcarpet: 
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", 
		                 "tables", "with_toc_data"]

defaults:
  -
    scope:
      path: "" 
    values:
      layout: "page"
      repository: UPnP-Device-Architecture-2.0
      project: "UPnP Device Architecture 2.0"
